name: Publish to PyPI/TestPyPI

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Publish target"
        required: true
        default: "pypi"
        type: choice
        options: [pypi, testpypi]
  release:
    types: [published]

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install build tooling
        run: python -m pip install --upgrade pip build
      - name: Build sdist and wheel
        run: python -m build
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish-testpypi:
    name: Publish to TestPyPI
    needs: build
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'testpypi' || (github.event_name == 'release' && github.event.release.prerelease) }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: testpypi
      url: https://test.pypi.org/p/note-to-json
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist/

  publish-pypi:
    name: Publish to PyPI
    needs: build
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'pypi' || (github.event_name == 'release' && !github.event.release.prerelease) }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: pypi
      url: https://pypi.org/p/note-to-json
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
